import { Inter, Raleway } from 'next/font/google'
import "funuicss/css/fun.css"
import "@/assets/css/globals.css"

const my_font = Raleway({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={my_font.className}>{children}</body>
    </html>
  )
}
